name: 'Terragrunt Directory Check'
author: 'Jared Zieche'
description: |
  Check files to determine paths for running infrastructure deployments via Terragrunt.
inputs:
  files:
    description: 'Files to inspect in order to make a decision on deployment'
    required: true
  base_directory:
    description: 'The base directory relative to the repo root from which to capture paths'
    required: true
    default: 'src/terraform'
  providers:
    description: 'Types of terraform providers to capture'
    required: true
    default: "aws"
  environments:
    description: 'What are the names of the environments to check for'
    required: true
    default: "sbx"
  regions:
    description: 'What are the available regions to deploy in'
    required: true
    default: "us-west-1"
  resource_groups:
    description: 'Regex patterns to match that determines which directories terragrunt can be executed from'
    required: true
    default: "cluster"
  global_files:
    description: 'List of paths to files that effect all environments'
    required: false
outputs:
  matrix:
    description: 'The include matrix that will be used to generate jobs.'
    value: ${{ steps.tg-dir-check.outputs.matrix }}
runs:
  using: 'docker'
  image: './Dockerfile'
branding:
  icon: 'grid'
  color: 'green'
