name: "build"
on:
  pull_request:
    types: [opened]
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "docs/*"
      - ".github/**"
      - ".git*"
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - "README.md"
      - "docs/*"
      - ".github/**"
      - ".git*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      default-matrix: ${{ steps.test-defaults.outputs.matrix }}
      inputs-matrix: ${{ steps.test-inputs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test-defaults
        with:
          test: true
      - uses: ./
        id: test-inputs
        with:
          base-directory: 'examples/src/terraform'
          providers: 'aws|azure'
          environments: 'sbx|dev|stage|prod'
          regions: 'us-west-1|us-east-1'
          resource_groups: 'cluster|lambda'
          test: true

  matrix:
    if: github.event_name == 'workflow_dispatch'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test.outputs.matrix) }}
    steps:
      - run: |
          echo "provider=${{ matrix.provider }}" >> $GITHUB_OUTPUT
          echo "env=${{ matrix.env }}" >> $GITHUB_OUTPUT
          echo "region=${{ matrix.region }}" >> $GITHUB_OUTPUT
          echo "resource_group=${{ matrix.resource_group }}" >> $GITHUB_OUTPUT
      - run: |
          echo "Planning ${{ format('{0}/{1}/{2}/{3}', matrix.provider, matrix.env, matrix.region, matrix.resource_group) }}" >> $GITHUB_STEP_SUMMARY
